spring:
  application:
    name: naming-server
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
management:
  server:
    port: 9200
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,metrics"
